name: Create Dev Zip

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLUGIN_SLUG: dintero-checkout-for-woocommerce

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install dependencies and build project
      run: |
        composer install
        composer install --no-dev

    - name: Define variables branch name, commit hash and zip file name
      id: vars
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
        COMMIT_HASH=$(git rev-parse --short HEAD)
        ZIP_FILE_NAME="${{ env.PLUGIN_SLUG }}-dev-${BRANCH_NAME}-${COMMIT_HASH}"
        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
        echo "COMMIT_HASH=${COMMIT_HASH}" >> $GITHUB_ENV
        echo "ZIP_FILE_NAME=${ZIP_FILE_NAME}" >> $GITHUB_OUTPUT

    - name: Attach branch name and commit hash to plugin version
      run: |
        sed -i "s/^ \* Version: \(.*\)/ \* Version: \1-dev.${BRANCH_NAME}.${COMMIT_HASH}/" ${{ env.PLUGIN_SLUG }}.php

    - name: Generate and upload plugin zip
      uses: krokedil/action-wordpress-plugin-build-zip@krokedil-improvements
      id: generate_and_upload_zip
      env:
        SLUG: ${{ env.PLUGIN_SLUG }}
      with:
        retention-days: 5 # Optional; defaults to 5
        artifact-name: ${{ steps.vars.outputs.ZIP_FILE_NAME }} # Optional; defaults to the repository name
        upload-plugin-artifact: true # Optional; defaults to true

    - name: Add annotation to workflow run with dev zip information
      run: echo "::notice::Dev Zip created and uploaded as artifact and available for 30 days. Please note that the artifact url is not publicly available."